### ISSUE TITLE
orgwide update

### ISSUE THREAD

**Issue by stvnrlly** [DCgov/orgwide#4]
This command would check which installed script bundles have updates, but would not apply the updates.

Like `brew outdated`, we may want to maintain a list of which bundles are `upgrade`-able.

**Comment by emanuelfeld** [comment]
Include a version in the metadata to check against.

**Comment by stvnrlly** [comment]
I was thinking that `git` would know whether or not there's been an update when `git fetch` is run inside of the repo.
